SensRoom/Models/ErrorViewModel.cs
using System;

namespace SensRoom.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SensRoom/Models/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SensRoom.Models
{
    public class RegisterViewModel
    {
        public string name { get; set; }
        public string pass { get; set; }
        public string confPass { get; set; }
        public bool tyc { get; set; }
        public string error { get; set; }
    }
}

SensRoom/Controllers/CRegistroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace SensRoom.Controllers
{
    public class CRegistroController : Controller
    {
        // GET: CRegistro
        public ActionResult Index()
        {
            return View();
        }

        // GET: CRegistro/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CRegistro/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CRegistro/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CRegistro/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CRegistro/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CRegistro/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CRegistro/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SensRoom/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SensRoom.Models;

namespace SensRoom.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SensRoom/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SensRoom.Models;

namespace SensRoom.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View("Login");
        }

        // GET: Login/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Login/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Login/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Login/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Login/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Login/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Login/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

      
        public ActionResult CreateUser()
        {
            return View("CreateUser");
        }

        public ActionResult CreateUserAccount(RegisterViewModel model)
        {
            if (model.tyc)
            {                
                return View("CreateUser");
            }
            else
            {
                model.tyc = true;
                model.error = "Es necesario aceptar los términos y condiciones para cntinuar";
                return View("CreateUser", model);
            }
         
        }
    }
}

SensRoom/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
    <link href="~/css/gobalHome.css" rel="stylesheet" />
    <link href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" rel="stylesheet">
    
    <header class="showcase">
        <div class="showcase-top">

            <a href="~/login" class="btn btn-rounded">Iniciar Sesión</a>
        </div>
        <div class="showcase-content">
            <img src="~/img/logo_sr.png" alt="" />
            <h1>Lorem ipsum dolor sit amet</h1>
            <p>Duis autem vel eum iriure dolor in hendrerit in vulputate</p>
            <a href="#all-moreinfo" class="btn btn-xl" data-scroll2 data-toggle="smooth-scroll" data-offset="0">
                CONOCER MÁS <i class="fas fa-chevron-right btn-icon"></i>
            </a>
        </div>
    </header>
	<section id="all-moreinfo" class="woman-content">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-5 col-lg-5">
                    <h2 class="text-lg text-shadow-2">
                        Placer y privacidad, todo en un lugar
                    </h2>
                    <p class="mb-20  text-shadow-2">Donec vestibulum nec felis ut dictum. Suspendisse dictum lorem id neque facilisis feugiat.</p>
                    <a href="~/login/CreateUser" class="btn btn-lg">REGISTRARSE</a>
                </div>
            </div>
        </div>
		
	</section>
	<section class="device-all">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-12">
					<img src="~/img/device-pile.png" />
				</div>
                <div class="col-lg-4 col-md-12">
                    <h2 class="text-lg text-shadow-2">
                        Donde sea y en cualquier dispositivo
                    </h2>
                    <p class="mb-20  text-shadow-2">Donec vestibulum nec felis ut dictum. Suspendisse dictum lorem id neque facilisis feugiat.</p>
                    <a href="~/login/CreateUser" class="btn btn-lg">REGISTRARSE</a>
                </div>
			</div>
		</div>
	</section>
	<footer class="footer">
        <div class="container full">
            <div class="row">
                <div class="col-12 col-lg-6 col-md-6 blok-code">
                    <p>
                        Si cuentas con un código de registro, favor de colocarlo a continuación
                    </p>
                    <div class="input-group mb-3">
                        <input type="text" class="form-control" placeholder="Código de registro" aria-label="Código de registro" aria-describedby="button-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button" id="button-addon2">INGRESAR</button>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-6 col-md-6">
                    <div class="row">
                        <div class="col-12 col-md-6 col-lg-4">
                            <ul>
                                <li><a href="#">Preguntas Frecuentes</a></li>
                                <li><a href="#">Formas de pago</a></li>
                                <li><a href="#">Terminos de Uso</a></li>
                            </ul>
                        </div>
                        <div class="col-12 col-md-6 col-lg-4">
                            <ul>
                                <li><a href="#">Cuenta</a></li>
                                <li><a href="#">Privacidad</a></li>
                                <li><a href="#">Aviso Legal</a></li>
                            </ul>
                        </div>
                        <div class="col-12 col-md-6 col-lg-4 social-list">
                            <h6>Contacto</h6>
                            <a href="#" target="_blank">
                                <i class="fas fa-envelope h4"></i>
                            </a>

                            <a href="#" target="_blank">
                                <i class="fab fa-instagram h4"></i>
                            </a>

                            <a href="#" target="_blank">
                                <i class="fab fa-twitter h4"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</footer>

SensRoom/Views/Login/CreateUser.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSystem.cshtml";
    ViewData["Title"] = "Create User";
}

@using (Html.BeginForm("CreateUserAccount", "Login", FormMethod.Post))
{

    @if (Model != null)
    {
        if (Model.tyc)
        {
            <div id="mensaje2" class="mensaje-alert">
                @Model.error
            </div>

        }
    }

    <!-- Signup Form -->
    <div class="app-contant">
        <div class="bg-dark">
            <div class="container-fluid p-0">
                <div class="row no-gutters">
                    <div class="col-sm-6 col-lg-5 col-xxl-3  align-self-center order-2 order-sm-1">
                        <div class="d-flex align-items-center h-100-vh">
                            <div class="register p-50">
                                <div class="text-center mb-4">
                                    <a href="~/"><img src="~/img/logo_sr.png" width="50%" /></a>
                                </div>
                                <h1 class="mb-2 text-center">Crear Usuario</h1>
                                <p class="text-center">Bienvenido, favor de crear cuenta</p>
                                <form action="login.cshtml" class="mt-3 mt-sm-5">
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label class="control-label" for="Alias">Elija Usuario</label>
                                                <input type="text" id="txtAlias" name="Alias" class="form-control" placeholder="6 a 12 caracteres sin espacios" />
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label class="control-label" for="Pass1">Ingresa una contraseña</label>
                                                <input type="password" id="Pass1" name="Pass1" class="form-control" placeholder="Ingresar contraseña" />
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="form-group">
                                                <label class="control-label" for="confPass">Vuelva colocar la misma contraseña</label>
                                                <input type="password" id="Pass2" name="confPass" class="form-control" placeholder="Confirmar contraseña" />
                                            </div>
                                        </div>
                                        <div class="col-12">
                                            <div class="d-block d-sm-flex  align-items-center">
                                                <div class="form-check">
                                                    <input class="form-check-input" type="checkbox" id="acepto-terminos">
                                                    <label class="form-check-label" for="acepto-terminos">
                                                        <a href="@Url.Action("tyc", "CRegistro")">Acepto términos y condiciones</a>
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-12 mt-3">
                                            <input type="submit" class="btn btn-primary text-uppercase" value="Crear cuenta" />
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 col-xxl-9 col-lg-7 bg-sensroom o-hidden order-1 order-sm-2">
                        <div class="row align-items-center h-100">
                            <div class="col-7 mx-auto ">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}
<!--end login contant-->

SensRoom/Views/Login/login.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSystem.cshtml";
    ViewData["Title"] = "login";
}

<!--start login contant-->
<div class="app-contant">
    <div class="bg-dark">
        <div class="container-fluid p-0">
            <div class="row no-gutters">
                <div class="col-sm-6 col-lg-5 col-xxl-3  align-self-center order-2 order-sm-1">
                    <div class="d-flex align-items-center h-100-vh">
                        <div class="login p-50">
                            <div class="text-center mb-4">
                                <a href="~/"><img src="~/img/logo_sr.png" width="50%" /></a>
                            </div>
                            <h1 class="mb-2 text-center">Iniciar Sesión</h1>
                            <p class="text-center">Bienvenido nuevamente, favor de ingresar sus credenciales.</p>
                            <form action="login.cshtml" class="mt-3 mt-sm-5">
                                <div class="row">
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label class="control-label">Usuario</label>
                                            <input type="text" class="form-control" placeholder="Nombre de usuario" />
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label class="control-label">Contraseña</label>
                                            <input type="password" class="form-control" placeholder="Colocar contraseña" />
                                        </div>
                                    </div>
                                    <div class="col-12">
                                        <div class="d-block d-sm-flex  align-items-center">
                                            <div class="form-check">
                                                <input class="form-check-input" type="checkbox" id="gridCheck">
                                                <label class="form-check-label" for="gridCheck">
                                                    Recordarme
                                                </label>
                                            </div>
                                            <a href="javascript:void(0);" class="ml-auto">¿Olvidaste la contraseña ?</a>
                                        </div>
                                    </div>
                                    <div class="col-12 mt-3">
                                        <a href="index.html" class="btn btn-primary text-uppercase">Entrar</a>
                                    </div>
                                    <div class="col-12  mt-3">
                                        <p>¿No tienes una cuenta ?<a href="~/login/CreateUser"> Registrarme</a></p>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-xxl-9 col-lg-7 bg-sensroom o-hidden order-1 order-sm-2">
                    <div class="row align-items-center h-100">
                        <div class="col-7 mx-auto ">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--end login contant-->

SensRoom/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SensRoom</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" rel="stylesheet">
</head>
<body>
    <!-- begin pre-loader -->
    <div class="loader">
        <div class="h-100 d-flex justify-content-center">
            <div class="align-self-center">
                <img src="~/img/loader/puff.svg" alt="loader">
            </div>
        </div>
    </div>
    <!-- end pre-loader -->
    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/smooth-scroll/smooth-scroll.min.js"></script>
    <script src="~/js/globalHome.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SensRoom/Views/Shared/_LayoutSystem.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SensRoom</title>
    <!-- google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" rel="stylesheet">
    <!-- System Style -->
    <link href="~/css/system.css" rel="stylesheet" />
</head>
<body class="bg-dark">
    <!-- begin app -->
    <div class="app">
        <div class="app-wrap">
            <!-- begin pre-loader -->
            <div class="loader">
                <div class="h-100 d-flex justify-content-center">
                    <div class="align-self-center">
                        <img src="~/img/loader/puff.svg" alt="loader">
                    </div>
                </div>
            </div>
            <!-- end pre-loader -->
            @RenderBody()

            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            <!--Sytem AppFront Scripts -->
            <script src="~/js/appFront.js"></script>
            @RenderSection("Scripts", required: false)
        </div>
    </div>
        <!-- end app -->
</body>
</html>